### PR TITLE
biocache related

### PR DESCRIPTION
**Pull request by shahmanash**
the generic-hub service does not connect to biocache-service as it cannot identify the hostname

### CODE REVIEW

**Comment by mskyttner** [comment]
The container needs to "see" and resolve the hostname used. That can be tested with "ping" for example. If this doesn't work from inside the container, then there is a problem. 

Perhaps https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/ can provide instructions on how to make the container see itself under a given hostname?

What about --link or --hostname and the docker compose equivalents, whatever those might be? 

Perhaps extra_hosts or external_links? It seems you can do this in docker-compose.yml:

domainname: foo.com
hostname: foo

Details: https://docs.docker.com/compose/compose-file/#/cpu-shares-cpu-quota-cpuset-domainname-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-shm-size-stdin-open-tty-user-working-dir

**Comment by mskyttner** [comment]
@shahmanash just checking, is this ready to test now, for example does the hostname "work"? 

Is this file needed: tomcat/biocache-cli-files/solr-template/biocache/conf/spellings.txt?

**Comment by shahmanash** [comment]
Not yet, added the biocache-cli, about the mentined files , i am not sure if it is mandatory to have the particular file or files , in any case the random content has to be removed while tidying up the code.

**Comment by shahmanash** [comment]
@mskyttner the hostname resolution from within container is still not fixed, nginx container was added
http:/gbifsweden.se/generic-hub is not working

**Comment by mskyttner** [comment]
This works for me, :+1:, merging.

**Pull request merged**
